### PR TITLE
Change the termBase for accountless mode

### LINKED ISSUE #152: Ferdium Help menu has broken options
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.36

### What Operating System are you using?

Windows

### Operating System Version

Win10

### What arch are you using?

x64

### Last Known Working Ferdium version

_No response_

### Expected Behavior

Proper URLs be opened for:

Help->Support 
Help->Terms of Service
Help->Privacy Statement

### Actual Behavior

Instead for Support, goes to: https://ferdium.org/contact (404, page not found)
other two attempt to find/upload/select a file??

### Steps to reproduce

Help->Support 
Help->Terms of Service
Help->Privacy Statement

### Debug link

_No response_

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Change the termBase for accountless mode

#### Motivation and Context
This fixes #152.
Although this provides an easy fix for the problem, do we want to keep it this way? This implementation forwards the Privacy Statement and the Terms of Service on the Help menu to the Ferdium API if no server is selected (accountless mode). This may be something we don't want to do given the fact that https://api.ferdium.org/terms.html has some terms related with Accounts and https://api.ferdium.org/privacy.html to data collection - which is not true when he have an accountless option.

Maybe providing a different file (maybe a local one) for terms and privacy when in accountless mode should be a better solution. Regardless, I'll keep this PR open so the discussion can happen.

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

File: src/api/apiBase.ts [hunk 1]
```diff
@@ -35,7 +36,12 @@ const apiBase = (withVersion = true) => {
 export default apiBase;
 
 export function termsBase() {
-  return fixUrl((window as any).ferdium.stores.settings.all.app.server !== LIVE_FRANZ_API
-    ? (window as any).ferdium.stores.settings.all.app.server
-    : DEV_API_FRANZ_WEBSITE);
+
+  const terms = (window as any).ferdium.stores.settings.all.app.server !== LIVE_FRANZ_API
```
Comment (vraravam) [inline src/api/apiBase.ts]: Can we remove the repetitive code please into a local constant?

**Review by vraravam — CHANGES_REQUESTED** [review]

File: src/api/apiBase.ts (hunk 1 above)
Comment (nathanaelhoun) [reply src/api/apiBase.ts]: Instead of a nested ternary operator, a `switch` could also do the trick

**Review by vraravam — APPROVED** [review]
Looks much cleaner. Thanks for the suggestion @nathanaelhoun
