### PR TITLE
fix: screenshare feature not working on Teams

### LINKED ISSUE #1598: "New" Teams can't screenshare on Windows
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.7.1-nightly.24

### Recipe Name

Microsoft Teams

### Recipe Version

3.3.0

### Last Known working version of the recipe

_No response_

### Steps to reproduce

1. Add Microsoft Teams Service into Ferdium
2. Login
3. ( if not already ) enable the "new Teams experience"
4. Start a meeting
5. Try starting screenshare

### Expected Behavior

The Portal should open with the rtc dialog prompting for the window/display to capture.

### Actual Behavior

The Dialog does not appear and this gets logged into the console:

```
VM715:6 This document requires 'TrustedHTML' assignment.
(anonymous) @ VM715:6
await in (anonymous) (async)
window.navigator.mediaDevices.getDisplayMedia @ VM715:2
(anonymous) @ calling-pluginless-1aad1fad9b044fc9.js:1
Promise.then (async)
getStream @ calling-pluginless-1aad1fad9b044fc9.js:1
request @ calling-pluginless-1aad1fad9b044fc9.js:1
(anonymous) @ calling-pluginless-1aad1fad9b044fc9.js:1
Promise.then (async)
add @ calling-pluginless-1aad1fad9b044fc9.js:1
getStream @ calling-pluginless-1aad1fad9b044fc9.js:1
getOrCreateMediaStream @ calling-pluginless-1aad1fad9b044fc9.js:1
startStream @ calling-pluginless-1aad1fad9b044fc9.js:1
start @ calling-pluginless-1aad1fad9b044fc9.js:1
start @ calling-pluginless-1aad1fad9b044fc9.js:1
getMediaStream @ calling-pluginless-1aad1fad9b044fc9.js:1
getMediaStream @ calling-pluginless-1aad1fad9b044fc9.js:1
createDevicesHandle @ calling-pluginless-1aad1fad9b044fc9.js:1
getScreenHandle @ calling-pluginless-1aad1fad9b044fc9.js:1
startScreenSharing @ calling-pluginless-1aad1fad9b044fc9.js:1
executeInternal @ calling-pluginless-1aad1fad9b044fc9.js:1
checkPendingOperationAndExecute @ calling-pluginless-1aad1fad9b044fc9.js:1
execute @ calling-pluginless-1aad1fad9b044fc9.js:1
f @ calling-pluginless-1aad1fad9b044fc9.js:1
r.value @ calling-pluginless-1aad1fad9b044fc9.js:1
h @ 948843-0ee3c6ef3cc7c2bb.js:1
(anonymous) @ 948843-0ee3c6ef3cc7c2bb.js:1
(anonymous) @ v2/:1
d @ v2/:1
startScreenSharingOnCall @ 948843-0ee3c6ef3cc7c2bb.js:1
(anonymous) @ 855309-820851879f408fbf.js:1
Promise.then (async)
(anonymous) @ 855309-820851879f408fbf.js:1
startSharing @ 855309-820851879f408fbf.js:1
startSharing @ 855309-820851879f408fbf.js:1
(anonymous) @ 889975-3ac235ee37448f28.js:1
a @ v2/:1
Promise.then (async)
c @ v2/:1
(anonymous) @ v2/:1
d @ v2/:1
startSharing @ 889975-3ac235ee37448f28.js:1
Ie @ 512161-03fcfdccb1994194.js:1
he @ 512161-03fcfdccb1994194.js:1
(anonymous) @ 512161-03fcfdccb1994194.js:1
(anonymous) @ 512161-03fcfdccb1994194.js:1
(anonymous) @ 512161-03fcfdccb1994194.js:1
(anonymous) @ 512161-03fcfdccb1994194.js:1
fe @ 512161-03fcfdccb1994194.js:1
(anonymous) @ supermassive-incremental-link-c535598fa8225f98.js:1
Promise.then (async)
(anonymous) @ supermassive-incremental-link-c535598fa8225f98.js:1
(anonymous) @ async-entry-36674d553fd0a95b.js:30
e @ 624497-5c350f865d27eb99.js:1
t.subscribe @ 624497-5c350f865d27eb99.js:1
(anonymous) @ async-entry-36674d553fd0a95b.js:30
Promise.then (async)
(anonymous) @ async-entry-36674d553fd0a95b.js:30
e @ 624497-5c350f865d27eb99.js:1
t.subscribe @ 624497-5c350f865d27eb99.js:1
(anonymous) @ 461286-bff149ff789280e5.js:1
e @ 624497-5c350f865d27eb99.js:1
t.subscribe @ 624497-5c350f865d27eb99.js:1
complete @ 461286-bff149ff789280e5.js:1
t.start @ 461286-bff149ff789280e5.js:1
t @ 461286-bff149ff789280e5.js:1
e.getObservableFromLink @ 461286-bff149ff789280e5.js:1
(anonymous) @ 461286-bff149ff789280e5.js:1
(anonymous) @ 461286-bff149ff789280e5.js:1
(anonymous) @ v2/:1
(anonymous) @ v2/:1
(anonymous) @ v2/:1
d @ v2/:1
e.mutate @ 461286-bff149ff789280e5.js:1
e.mutate @ 461286-bff149ff789280e5.js:1
(anonymous) @ async-entry-36674d553fd0a95b.js:30
(anonymous) @ v2/:1
d @ v2/:1
mutate @ async-entry-36674d553fd0a95b.js:30
(anonymous) @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ v2/:1
d @ v2/:1
_startScreenshareFromCall @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ v2/:1
d @ v2/:1
_onScreenSharingStarting @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ v2/:1
d @ v2/:1
shouldCheckForOfficeWindowShareInterceptFlow @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ v2/:1
d @ v2/:1
_onPreviewClicked @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ share-tray-337d0d03eaeeb157.js:1
(anonymous) @ 119579-568b6df4704e6f22.js:1
(anonymous) @ 119579-568b6df4704e6f22.js:1
Be @ 722183-a977a2d4c22ae7a6.js:1
Ke @ 722183-a977a2d4c22ae7a6.js:1
(anonymous) @ 722183-a977a2d4c22ae7a6.js:1
Pr @ 722183-a977a2d4c22ae7a6.js:1
Nr @ 722183-a977a2d4c22ae7a6.js:1
(anonymous) @ 722183-a977a2d4c22ae7a6.js:1
De @ 722183-a977a2d4c22ae7a6.js:1
(anonymous) @ 722183-a977a2d4c22ae7a6.js:1
Rr @ 722183-a977a2d4c22ae7a6.js:1
Jn @ 722183-a977a2d4c22ae7a6.js:1
Zn @ 722183-a977a2d4c22ae7a6.js:1
n.unstable_runWithPriority @ 722183-a977a2d4c22ae7a6.js:1
Hl @ 722183-a977a2d4c22ae7a6.js:1
Me @ 722183-a977a2d4c22ae7a6.js:1
Xn @ 722183-a977a2d4c22ae7a6.js:1

```

### Screenshots

_No response_

### Additional Information

~~My private PC with Linux on 6.7.6 + Wayland is not affected.~~
Affected on 6.8.2 Wayland/X11 as well

My company enforces the new teams tho where I am forced to use Windows.
It's Windows 10 22H2 as of now.
The screensharing worked using the "old" teams.

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
Fixed screenshare on new Teams (v2) and possibly other services

#### Motivation and Context
This fixes https://github.com/ferdium/ferdium-app/issues/1598 and possibly other issues related with screenshare.

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [x] `pnpm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes

Fixed screenshare issue on new Teams (v2) and possibly other services

### CODE REVIEW

**Review by vraravam — APPROVED** [review]
tested on m2 mac - working! lgtm!

File: src/components/MediaSource.tsx [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+  ipcRenderer.on(`select-capture-device:${service.id}`, (_event, data) => {
+    setShow(true);
+    setTrackerId(data.trackerId);
+  });
+
+  useEffect(() => {
+    ipcRenderer
+      .invoke('get-desktop-capturer-sources')
+      .then(sources => setSources(sources));
+  }, []);
```
Comment (SpecialAro) [inline src/components/MediaSource.tsx:25]: This is causing the issue Ajunne just reported on Discord.

Comment (SpecialAro) [reply src/components/MediaSource.tsx:25]: Fixed in https://github.com/ferdium/ferdium-app/pull/1736
