### PR TITLE
Fix notifications on all services

### LINKED ISSUE #896: Bug: Notifications on Element counted twice
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.3

### What Operating System are you using?

Windows

### Operating System Version

macOS 13.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

_No response_

### Expected Behavior

Notifications should be counted only once.

### Actual Behavior

Notifications of rooms marked as "favourite" are counted twice.

### Steps to reproduce

1. Right click on a room and choose "Favourited"
2. Wait until you receive a notification on that room
3. Element displays notification bubble (1) on the group which contains the room as well as bubble (1) on the "Favourites" group (the button with the star).
4. Ferdium displays (2) notifications. 

### Debug link

_No response_

### Screenshots

image

In this screenshot, the two notifications in the "Favourites" group [★] refer to the same two messages as the two notifications on group [B].

### Additional information

Apparently, the notifications from Element are simply added by Ferdium. That's okay, but the number from the "Favourites" group (the button with the star) must be ignored in order to avoid duplicates.

### LINKED ISSUE #1105: No notifications
### Your issue

we don't receive any notifications from apps,  all messages on my apps are not receiving any notifications, the number of incoming messages is displayed next to the icon but there is no notification of new messages how can i fix this problem?

### LINKED ISSUE #1652: new Notification throws exception
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.2

### What Operating System are you using?

Other (specify below)

### Operating System Version

This happens across systems. I was able to reproduce it on Windows and Linux

### What arch are you using?

x64

### Last Known Working Ferdium version

_No response_

### Expected Behavior

I'd expect `new Notification("foo", { body: "bar" });` returns nothing.

### Actual Behavior

Running (from dev console or from embedded app) `new Notification("foo", { body: "bar" });` generates exception:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'then')
    at new Notification (<anonymous>:18:13)
    at <anonymous>:1:22
```

I believe this is not correct? I have arrived at this issue debugging Element being broken in Ferdium. It does not display new messages correctly. However I think the issue isn't specific to Element, just that Element fails to show the message after getting the exception thrown at it.

In case that helps, here's the error from console when Element tries to display notification (but again I believe the issue is more generic, I just happened to hit it with Element):

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'then')
    at new Notification (<anonymous>:18:13)
    at Z.displayNotification (BasePlatform.ts:209:30)
    at H.displayPopupNotification (Notifier.ts:173:28)
    at H.evaluateEvent (Notifier.ts:506:22)
    at Me.<anonymous> (Notifier.ts:448:14)
    at o.emit (events.js:158:7)
    at Me.emit (typed-event-emitter.ts:89:22)
    at _.t (ReEmitter.ts:55:29)
    at o.emit (events.js:158:7)
    at _.emit (typed-event-emitter.ts:89:22)
```

I'm not proficient in JS, so above are just my assumptions after a bit of debugging.

### Steps to reproduce

1. open service developer tools (ctrl + shift + alt + i) in any app that has notifications enabled.
2. In console run `new window.Notification("foo", { body: "bar" });`

### Debug link

_No response_

### Screenshots

_No response_

### Additional information

_No response_

### LINKED ISSUE #1719: Android Messages content is always shown in notifications
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.7.2

### Recipe Name

Android Messages

### Recipe Version

2.4.0

### Last Known working version of the recipe

_No response_

### Steps to reproduce

1. In Ferdium go to Settings -> Privacy. Enable "Don't show message content in notifications" option.
2. Send SMS message to your mobile number.
3. Look at notification - you will see message content.

### Expected Behavior

You should not see the message content.

### Actual Behavior

You will see the message content.

### Screenshots

_No response_

### Additional Information

_No response_

### LINKED ISSUE #1747: RocketChat double notifications
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.3

### What Operating System are you using?

Other Linux

### Operating System Version

Fedora 40 - 6.8.8-300.fc40.x86_64

### What arch are you using?

x64

### Last Known Working Ferdium version

_No response_

### Expected Behavior

Notifications should be counted only once.

### Actual Behavior

Notifications are send twice.

### Steps to reproduce

1. Receive a message in RocketChat Channels or Chats.
2. Receive every desktop notification twice (Gnome notifications).

### Debug link

_No response_

### Screenshots

_No response_

### Additional information

_No response_

### LINKED ISSUE #1751: annoyning message-box notifications by ferdium for ms-teams
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.3

### What Operating System are you using?

Ubuntu

### Operating System Version

23.04

### What arch are you using?

x64

### Last Known Working Ferdium version

_No response_

### Expected Behavior

I would expect push-notifications that automatically disappear after given time.  I already disabled notifications for ms-teams service in ferdium, but the annoying notifications still appear for every(!) message.

### Actual Behavior

Every message will show-up a message-confirm box like this!
image

### Steps to reproduce

I don't know if or how this is reproduceable. I've recently upgraded ferdium and ferdium-recieipts including ms-teams and then it was there.

### Debug link

_No response_

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
Change notification class to extend `window.Notification`.

#### Motivation and Context
Several users are reporting that notifications don't work on several services (noticed that `icon` was not being shown properly)
Maybe fixes https://github.com/ferdium/ferdium-app/issues/1105
Fixes https://github.com/ferdium/ferdium-app/issues/1751
Fixes https://github.com/ferdium/ferdium-app/issues/1747
Fixes https://github.com/ferdium/ferdium-app/issues/896
Fixes https://github.com/ferdium/ferdium-app/issues/1719
Fixes https://github.com/ferdium/ferdium-app/issues/1652

Steps to fix this PR:
- [x] Fix the onClick function (not working since ever....) to properly open Ferdium (if closed), open the service, ~and go to the corresponding message on a service (new feature)~. (I was not able to implement this last logic... it's rather complex. Leaving for the future).
- [x] For some reason, this new approach is spawning two notifications (I think that the first one is from window.Notification natively and that the other one is our class Notification). Nevertheless, clicking on the latest notification closes all notifications. Need help fixing this (@vraravam if you can take a look at this please) - or should we merge this PR with a "Known issue" for this?

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [x] `pnpm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes

Fixed several issues with notifications (double notifications, no icons on notification, content showing when private).
Added feature to open Ferdium and go to the specific service after clicking the notification.

### CODE REVIEW

File: src/webview/notifications.ts [hunk 1]
```diff
@@ -31,52 +31,29 @@ export class NotificationsHandler {
...
+      // Continue to dispatch the event to the original Notification class
+      super.dispatchEvent(new Event('click'));
+    });
+  }
 
-    onNotify(data) {
-      return data;
+  static requestPermission(cb) {
+    if (typeof cb === 'function') {
+      cb(Notification.permission);
```
Comment (vraravam) [inline src/webview/notifications.ts:47]: does this need to `return` the returned value from the `cb` call?

Comment (SpecialAro) [reply src/webview/notifications.ts:47]: that's a great question, I'm not entirely sure if yes or no... Previously we were returning, maybe we can see if the same still works

**Comment by SpecialAro** [comment]
Self-reminder: This PR should also address the issue here (https://github.com/ferdium/ferdium-app/issues/1751) that was introduced by the `extend window.Notifications`

File: src/webview/notifications.ts (hunk 1 above)
Comment (SpecialAro) [reply src/webview/notifications.ts:47]: I think the callback is deprecated (but leaving here for old website implementations)
https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission_static
