### PR TITLE
Fix issue with accent color

### LINKED ISSUE #2017: Not showing Interface : Completely Blank Interface is showing
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

Ferdium-linux-Portable-7.0.0-x86_64

### What Operating System are you using?

Ubuntu

### Operating System Version

Linux mint 22.1

### What arch are you using?

x64

### Last Known Working Ferdium version

Ferdium-linux-Portable-7.0.0-x86_64

### Expected Behavior

When I open the ferdium via appimage file running it as "execute as program" it runs but not showing the interface as you can see in the image Its all blank .
currentStatusOfFerdium

### Actual Behavior

Actually what happened is, I was playing with this app and trying to know about it and I liked it. 
But in the appearance section I tried to change colours but as I was doing it  started to shift to different colours put after some time it didn't revert back.
currentStatusOfFerdium

### Steps to reproduce

-- open app In linux mint 22.1 appimage/deb/flatpak whatever you wanna use ( I tried via appimage and deb packages).
-- go to appearance section try to change the color ( first option i think , that messed it up , my fav color is #0f011b as I was writing this ferdium gone completely blank )
-- after that it is still blank.

### Debug link

_No response_

### Screenshots

currentStatusOfFerdium
this is screenshot of current situation .

### Additional information

_No response_

### LINKED ISSUE #2047: Completely white window
### Avoid duplicates

- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

7.0.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 Pro 24H2

### What arch are you using?

x64

### Last Known Working Ferdium version

_No response_

### Expected Behavior

Be able to use Ferdium

### Actual Behavior

No matter if i close the app, reboot the pc, uninstall and install again, I only have a completely white window

Image

### Steps to reproduce

The first time it happened i was just deleting the colour code to return to default

### Debug link

_No response_

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
Fix issue with accent color

#### Motivation and Context
Fixes https://github.com/ferdium/ferdium-app/issues/2017
Fixes https://github.com/ferdium/ferdium-app/issues/2047
Users who got the settings.json corrupted from this need to manually change the `accentColor` and the `progressbarAccentColor` to a random color (default: `#7367F0`)

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [x] `pnpm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

File: src/helpers/color-helpers.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+type ColorMethod = 'hex' | 'rgb' | 'rgba' | 'hsl' | 'hsla' | 'named';
+
+export const isValidColor = (color: string, method?: ColorMethod): boolean => {
+  const patterns: Record<ColorMethod, RegExp> = {
+    hex: /^#(?:[\dA-Fa-f]{3}){1,2}$/,
```
Comment (Alphrag) [inline src/helpers/color-helpers.ts]: Do we want to accept hex with transparency? In which case, the expression should likely be:
```suggestion
    hex: /^#(?:[\dA-Fa-f]{3,4}){1,2}$/,
```

File: src/helpers/color-helpers.ts [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+    hsla: /^hsla\(\d{1,3}(?:,\s*\d{1,3}%){2},\s*[\d.]+\)$/,
+    named: /^[A-Za-z]+$/,
+  };
+
+  if (method) {
+    return patterns[method].test(color);
+  }
+
+  // Check all methods if no specific method is provided
+  return Object.values(patterns).some(regex => regex.test(color));
```
Comment (Alphrag) [inline src/helpers/color-helpers.ts:18]: Do we want to be more precise in the way we test the values, or shall we assume for now that users are giving correct values if they have managed to pass that regex?

File: src/components/settings/settings/EditSettingsForm.tsx [hunk 3]
```diff
@@ -384,6 +384,14 @@ class EditSettingsForm extends Component<IProps, IState> {
       e.preventDefault();
     }
 
+    // Do not submit if the accent color is not set
+    if (
+      this.props.form.$('accentColor').value === '#' ||
```
Comment (Alphrag) [inline src/components/settings/settings/EditSettingsForm.tsx:389]: Why not use the `isValidColor` you implemented in `color-helpers.ts` both for `accentColor` and for `progressbarAccentColor` directly here? And then remove the tests on lines 400 and 404?

Otherwise, we could do this inside the `form.submit` function below, and change the current lines 400-402 as follows:
```
if (accentColor.trim().length === 0 || !isValidColor(accentColor)) {
    values.accentColor = DEFAULT_ACCENT_COLOR;
}
```
and similarly for `progressbarAccentColor` on lines 404-406. That way we fully verify the user input. 

What do you think?

**Comment by Alphrag** [comment]
Thanks, the validator of the colour in regex is quite nice!
Side note: when running `pnpm prepare-code` it moved the import of the `DEFAULT_ACCENT_COLOR` variables a few lines above, so maybe rerunning it for you will also change it ^^

File: src/components/settings/settings/EditSettingsForm.tsx (hunk 3 above)
Comment (SpecialAro) [reply src/components/settings/settings/EditSettingsForm.tsx:389]: I've initially used that but I had to prevent the submit somehow - when the user is typing every keystroke submits to the file (I know this is not ideal, but it is how it is coded.... we would need to redo the entire logic to improve this at some point). So, in order to allow the user to input the hex, I can't tell it to submit "#", so I just prevent the submit entirely. It's a bit of a workaround.

But if you have any idea on how to code it better I would be up for improving this xD I just didn't gave it much thought myself as it was taking more time from me as it was supposed to (given the fact that is a simple issue --')

File: src/helpers/color-helpers.ts (hunk 2 above)
Comment (SpecialAro) [reply src/helpers/color-helpers.ts:18]: If we specify the regex then we obligatory test against that regex, otherwise (if we dont specify) we test all regexes and if one is true then it is, in fact, a color. No?

Comment (Alphrag) [reply src/helpers/color-helpers.ts:18]: Oh sorry forget I said that, I just did some tests and realised that even if the values are not in the expected range (like not between 0 and 255 for rgb) then it doesn't break anything, so there is no need to check the range of the values for each way colours can be put.

**Comment by SpecialAro** [comment]
> Thanks, the validator of the colour in regex is quite nice! Side note: when running `pnpm prepare-code` it moved the import of the `DEFAULT_ACCENT_COLOR` variables a few lines above, so maybe rerunning it for you will also change it ^^

Just did, thanks! :D
