### PR TITLE
Fix 195

### LINKED ISSUE #195: Bug: Discord immediately opens image on click on Linux
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

v6.0.0-beta.1

### What Operating System are you using?

Other Linux

### Operating System Version

Linux 5.17.9-arch1-1 KDE X11

### What arch are you using?

x64

### Last Known Working Ferdium version

last version of ferdi did not have this issue for me

### Expected Behavior

When clicking an image in Discord normally, a pop up with the image appears within the page with the option to open in browser.

### Actual Behavior

When I click on an image in Ferdium Discord, the image immediately opens in browser. I will never see the Discord image viewer.
The image viewer looks like this 
image

### Steps to reproduce

Click on any image on Discord within the ferdium app, the image will immediately open in browser instead.

### Debug link

_No response_

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Fix #195 

#### Motivation and Context
This PR is paired with https://github.com/ferdium/ferdium-recipes/pull/37 and should be merged first.
Together, both PRs fix #195, which causes a problem when opening images inside the discord (and possibly zoom).

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes
Fix problem with opening images within discord and zoom recipes.

### CODE REVIEW

File: src/webview/lib/RecipeWebview.ts [hunk 1]
```diff
@@ -92,6 +92,15 @@ class RecipeWebview {
     return this.badgeHandler.safeParseInt(text);
   }
 
+  /**
+   * Find if url contains image
+   *
+   * @param  {string | number | undefined | null} text to be parsed
+   */
+  isImage(url): boolean {
```
Comment (vraravam) [inline src/webview/lib/RecipeWebview.ts:100]: Doesn't this also need to be exposed in https://github.com/ferdium/ferdium-app/blob/develop/src/webview/recipe.js#L111-L119 ? Have you tested that this works without that addition?

**Review by vraravam — CHANGES_REQUESTED** [review]

File: src/webview/lib/RecipeWebview.ts (hunk 1 above)
Comment (SpecialAro) [reply src/webview/lib/RecipeWebview.ts:100]: Wondered the same when I did it, but I've tested locally and it worked.

Let me verify that again. If you can test it as well it would be nice.

Comment (SpecialAro) [reply src/webview/lib/RecipeWebview.ts:100]: image

Added a ``console.log('isImage', Ferdium.isImage(url));`` here:
image

And it works without exposing it (which is weird, again)...

Comment (vraravam) [reply src/webview/lib/RecipeWebview.ts:100]: cool. Tx. Resolving this comment

File: src/webview/lib/RecipeWebview.ts [hunk 2]
```diff
@@ -92,6 +92,15 @@ class RecipeWebview {
...
+    return /\.(jpg|jpeg|png|webp|avif|gif|svg)$/.test(url);
```
Comment (vraravam) [inline src/webview/lib/RecipeWebview.ts:101]: Is this going to return 1/0 or true/false?

Comment (SpecialAro) [reply src/webview/lib/RecipeWebview.ts:101]: True/false. I'm changing the docs to reflect this.

File: src/webview/lib/RecipeWebview.ts (hunk 1 above)
Comment (SpecialAro) [reply src/webview/lib/RecipeWebview.ts:100]: Also tested on MacOS and works.

**Review by vraravam — APPROVED** [review]
