### PR TITLE
Fix reload after resume and add idle time setting

### LINKED ISSUE #305: Bug: Reload after system resume not working
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly-58 and -69 tested

### What Operating System are you using?

Windows

### Operating System Version

10.0.19041 Build 19041

### What arch are you using?

x64

### Last Known Working Ferdium version

_No response_

### Expected Behavior

Ferdium should be just usable after system resume, e.g. after hibernation or longer standby times.

If this is not easily possible, at least the settings option "Reload after system resume" should trigger in these cases and issue a full app reload.

### Actual Behavior

After hibernation or longer standby times all Ferdium tabs are unloaded. I have to reload all (ctrl+shift+r) to continue.

### Steps to reproduce

1. Put your computer to sleep
2. Wait a while
    - I don't know how long exactly, but I've tested a bit:
    - Unfortunatley, a short sleep time is ok apparently (I immediately woke up my computer after putting it to sleep)
    - Also, a short hibernation time is also ok (I just used `shutdown /h /f` and immediately woke the computer up again)
    - So there has to be some kind of unkown timeout duration...?
4. Wake your computer
5. Find Ferdium unusable :(

### Debug link

_No response_

### Screenshots

_No response_

### Additional information

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Fix reload after resume and add idle time setting

#### Motivation and Context
Fix reload after resume and add idle time setting. This fixes https://github.com/ferdium/ferdium-app/issues/305
<sub>This time I didn't forgot the `en-us.json` file xD</sub>

#### Screenshots
image

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes

Fix reload after resume and add idle time setting

### CODE REVIEW

File: src/stores/AppStore.js [hunk 1]
```diff
@@ -232,9 +232,11 @@ export default class AppStore extends Store {
       debug('System resumed, last suspended on', this.timeSuspensionStart);
       this.actions.service.resetLastPollTimer();
 
+      const idleTime = this.stores.settings.app.reloadAfterResumeTime;
+
       if (
-        this.timeSuspensionStart.add(10, 'm').isBefore(moment()) &&
-        this.stores.settings.app.get('reloadAfterResume')
+        this.timeSuspensionStart.add(idleTime, 'm').isBefore(moment()) &&
+        this.stores.settings.app.reloadAfterResume
```
Comment (vraravam) [inline src/stores/AppStore.js:239]: This is an integer representing time in minutes - if so, then this if condition logic is incorrect

**Review by vraravam — CHANGES_REQUESTED** [review]

**Review by vraravam — APPROVED** [review]
