### PR TITLE
fix window icon for linux

### LINKED ISSUE #1978: [linux] no titlebar icon
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

7.0.0

### What Operating System are you using?

Other Linux

### Operating System Version

Debian testing
`Linux p14s 6.11.7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.11.7-1 (2024-11-09) x86_64 GNU/Linux`

### What arch are you using?

x64

### Last Known Working Ferdium version

never seen it working

### Expected Behavior

Opening ferdium program should include icon on titlebar.

### Actual Behavior

No icon on titlebar (refer to screenshot)

### Steps to reproduce

1. install i3wm (ver >= 4.20)
2. install ferdium (from either appimage or deb release)
3. open ferdium

### Screenshots

image
Note discord & signal show icons:
image

### Additional information

```
Version: 7.0.0
Server: No Server
Electron: 33.2.0
Chrome: 130.0.6723.118
Node.js: 20.18.0
Platform: Linux 6.11
Arch: x64
Build date: Sun Nov 10 2024 03:22:25 GMT+0100 (Central European Standard Time)
Git SHA: e6249427
Git branch: release
```

```sh
$ i3 --version
i3 version 4661e74+ © 2009 Michael Stapelberg and contributors
```

Note you need i3 v>=4.20 to have [window icons](https://i3wm.org/docs/userguide.html#title_window_icon) feature available. Additionally it requires following config item to enable it:
```
# enable window icons for all windows:
for_window [class=".*"] title_window_icon on
```

It is _not_ i3 problem as other, including electron-based, applications successfully result in icons, e.g. [bruno](https://github.com/usebruno/bruno)  & [Postman Canary](https://www.postman.com/downloads/canary/)

### PR DESCRIPTION
**Pull request by laur89**
fixes #1978

#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
This change adds `icon` property to main BrowserWindow config, given the build is for linux.

#### Motivation and Context

This change adds window icon for some window manager under linux that were broken until now, e.g. i3wm.
For context see #1978 or brief conversation on [discord](https://discord.com/channels/963836780778512454/964164239419916388/1309989567679692921)

#### Screenshots
See the related issue #1978

#### Checklist

- [x] My pull request is properly named
- [ ] The changes respect the code style of the project (`pnpm prepare-code`)
- [ ] `pnpm test` passes
- [x] I tested/previewed my changes locally

Note the two items are not checked as I built it via Dockerfile
#### Release Notes

Fix window icon for some Linux window managers (e.g. i3wm)

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -214,6 +214,13 @@ const createWindow = () => {
         DEFAULT_APP_SETTINGS.accentColor,
       ) as string);
 
+  const linuxMainWindowConf = {
+    icon: asarPath(join(
+      isDevMode ? `${__dirname}../src/` : __dirname,
+      'assets/images/icons/256x256.png',
+    ))
+  };
```
Comment (laur89) [inline src/index.ts]: Unsure whether we have to exclude this config for non-linux platforms, but I don't have access to others and can't be sure whether it might have adverse effects on windows/mac.

Comment (Alphrag) [reply src/index.ts]: Seems fine like this for me, affecting only linux assets.

**Review by Alphrag — APPROVED** [review]
Tested on cross-platforms (Windows, MacOS and Linux Debian) and it works as expected. Thanks @laur89!
